### ISSUE TITLE
Velg funksjoner (JavaScript)/fragmenter av markup-språket (HTML)/stilark (CSS), som eksisterer i de gitte rammeverkene, som egner seg for hvert steg i FS-SYSTEM-STEG.

### ISSUE THREAD

**Issue by buseliiik** [buseliiik/How-we-roll#15]
Alle funksjoner må dokumenteres (enten i kommentaren i koden eller i dokumenter i deres github reps)

**Comment by mienord** [comment]
Martin og Stein

**Comment by mienord** [comment]
Dere må velge funksjoner før vi kan velge tester: feks. dere velger funksjonene og koder for: slidere, buttons, header og linker i header, Canvas API - hvordan man kan tegne de prikkene/resultatene med det? 
Deretter kan Jeppe og jeg foreslå tester for disse funksjonene.

**Comment by mienord** [comment]
avaScript <form> elementet for å fylle inn informasjon

**Comment by mienord** [comment]
Slider + <form> - hvordan vi kan lagre og få informasjonen tilbake
